apiVersion: v1
kind: Secret
metadata:
  name: visit-counter-secret
  namespace: visit-counter
  labels:
    app: visit-counter
type: Opaque
data:
  # echo -n 'my-super-secret-api-key' | base64
  api-key: bXktc3VwZXItc2VjcmV0LWFwaS1rZXk=
